### ISSUE TITLE
Issue with texture translation

### ISSUE THREAD

**Issue by UnoCheSiAnnoia** [ImaterialC/PriconeTL#29]
I downloaded the textureless patch first, after I noticed I downloaded the wrong one I removed the files as indicated in the readme and downloaded the texture patch. After this, the textures still seem not to translate. 
A friend who downloaded the same patch without downloading the textureless patch first doesn't have this issue, so I think it might be part of the issue, though it might also be something on my PC that created some problems.

**Comment by ImaterialC** [comment]
Hello mate, we are under investigate this issue, you can see the news on our discord server.

**Comment by UnoCheSiAnnoia** [comment]
joined discord, do you prefer if i remove the issue on github and put it somewhere else on discord?

**Comment by ImaterialC** [comment]
that already on the annauncement
