### ISSUE TITLE
Unable to Completely Translate some Words on Windows 11

### ISSUE THREAD

**Issue by Pentlime** [ImaterialC/PriconeTL#30]
After i check, maybe it's because Windows 11 Security that make translator got restricted on a few part, and Online translation didn't work properly too, (Windows 11 22H2 ver.)

![Screenshot 2023-04-09 125518](https://user-images.githubusercontent.com/102337393/230757357-d86164d3-dd3c-4ee6-a5ed-d03ea2c733f8.png)
![Screenshot 2023-04-09 125916](https://user-images.githubusercontent.com/102337393/230757361-9fde1b65-fcb0-416e-a93e-473bf94fa859.png)

**Comment by tilda** [comment]
CNR
![image](https://user-images.githubusercontent.com/8301262/231052308-b4c083da-6e47-4815-b814-e60dee0e5640.png)

**Comment by touanu** [comment]
Guildhouse is not completed
If texture translation doesn't work, you can try alternative version in latest release
